services:
  - type: web
    name: valdez-elementary-school
    runtime: node
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
